/settings:
  get:
    operationId: getPartnerSettings
    tags:
      - Settings
    description: Retrieve all settings for this partner
    security:
      - bearerAuth: []
    parameters:
      - $ref: '../components/parameters.yaml#/MoniteVersion'
      - $ref: '../components/parameters.yaml#/MoniteEntityId'
    responses:
      '200':
        description: Partner settings retrieved successfully
        headers:
          x-monite-version:
            $ref: '../components/headers.yaml#/MoniteVersion'
          x-request-id:
            $ref: '../components/headers.yaml#/RequestId'
          x-process-time:
            $ref: '../components/headers.yaml#/ProcessTime'
          x-monite-entity-id:
            $ref: '../components/headers.yaml#/MoniteEntityId'
        content:
          application/json:
            schema:
              $ref: '../components/schemas/settings.yaml#/PartnerSettings'
      '400':
        $ref: '../responses/errors.yaml#/BadRequest'
      '401':
        $ref: '../responses/errors.yaml#/Unauthorized'
      '422':
        $ref: '../responses/errors.yaml#/UnprocessableEntity'
  
  patch:
    operationId: updateSettings
    tags:
      - Settings
    description: Update API settings including default version
    security:
      - bearerAuth: []
    parameters:
      - $ref: '../components/parameters.yaml#/MoniteVersion'
      - $ref: '../components/parameters.yaml#/MoniteEntityId'
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../components/schemas/settings.yaml#/PartnerSettings'
    responses:
      '200':
        description: Settings updated successfully
        headers:
          x-monite-version:
            $ref: '../components/headers.yaml#/MoniteVersion'
          x-request-id:
            $ref: '../components/headers.yaml#/RequestId'
          x-process-time:
            $ref: '../components/headers.yaml#/ProcessTime'
          x-monite-entity-id:
            $ref: '../components/headers.yaml#/MoniteEntityId'
        content:
          application/json:
            schema:
              $ref: '../components/schemas/settings.yaml#/PartnerSettings'
      '400':
        $ref: '../responses/errors.yaml#/BadRequest'
      '401':
        $ref: '../responses/errors.yaml#/Unauthorized'
      '422':
        $ref: '../responses/errors.yaml#/UnprocessableEntity'